version: '3.8'

services:
  nestjs-api:
    container_name: nestjs-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    links:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - '5000:5000'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    